# Dockerfile for React Client

# Use the official Node.js image as the base image
FROM node:16-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Build the React application
RUN npm run build

EXPOSE 3000

# Start Nginx when the container starts
CMD ["npm","start"]
